# Literature Review 

Grounded in the theories of social constructivism and cooperative learning, this chapter reviews the literature on critical thinking and examines how critical thinking can be fostered in online distance learning environments through encouraging students to take deeper approaches to their learning.

Despite extensive electronic searches of online databases, scholarly journals and university library catalogues, very few articles on the topic of cooperative study buddy activities in online distance learning contexts were found. Although the term “study buddy” was used quite often in research articles, it tended to refer either to unstructured, social partnerships between students or automated software solutions used to match potential study partners.

## Social Constructivism {-}

The theoretical foundation of modern forms of online distance learning can be traced back more than a century to the writings of Dewey (1910) and Vygotsky (1962, 1978), both of whom argue in one way or another that learning is a social activity.  Dewey was the first to describe the importance of a learner’s social context and the active construction of meaning in the learning process, and it was Vygotsky who provided educators with a research-based model that explained how people learn in social contexts.

Among Vygotsky’s significant contributions to the study and practice of teaching and learning was the idea that the best learning takes place in the “zone of proximal development” (ZPD) (Vygotsky, 1978, p. 84), which is the theoretical space between what a learner can do independently and what a learner cannot do, even with the help of a more capable peer or adult. A learner operating in the ZPD would be able to solve complex problems, but only with the assistance and coaching of someone else.

An important implication of the ZPD as described by Driscoll (2005) is that, while the lower boundary of the zone is fixed by the learner’s cognitive abilities, the upper limit can be moved through the effective design and implementation of learning environments. By providing appropriate scaffolds for learners, so that they are being challenged to do something that they are unable to do alone, effective learning environments lead the learners into higher levels of mental development (Glick, 2004).

Also important to note is the necessity of a more capable peer or adult in the learning process. Much like Dewey’s assertion that learning happens in the social world of the student, Vygotsky’s theory recognizes the importance of the learner’s social world in the learning process. Vygotsky asserts that learning first happens in a social context, when a learner interacts with a more capable peer, and then within the individual, when the learner has mastered and internalized the skill (Glick, 2004).

Vygotsky’s sociocultural theory is not the only social constructivist theory, but it has been very fruitful in terms of providing a basis for learning theories in contemporary times. One such theory, cooperative learning theory, has been studied extensively since the 1970s and may provide a good foundation for exploring the characteristics of the study buddy activity in this study.

## Cooperative Learning {-}

Cooperative learning is the pedagogical practice of structuring learning activities so that dyads or small groups of students work together in order to achieve the stated goal of the activity (Johnson & Johnson, 1999a; Slavin, 1980, 2011). Slavin (1980) contrasts cooperative activities with competitive and individualistic learning activities. Competitive activities are structured in such a way that the success of one student necessitates the relative failure of another student, whereas individual activities are those structured so that the achievement of one student has no effect on the achievement of other students. In comparison, cooperative activities are structured so that the success of one student is dependent upon and promotes the success of others. While some faculty may contend that they encourage or require students to work with partners and groups on a regular basis, a review of the literature on cooperative learning shows that unstructured group work is not as effective at improving achievement when compared to well-structured cooperative learning activities, the characteristics of which are described below (Johnson et al., 1994; Johnson, Johnson, & Stanne, 2000; Johnson & Johnson, 1999b).

Researchers (Johnson et al., 1994; Johnson & Johnson, 1999b) have identified five key characteristics of well-structured cooperative learning activities: positive interdependence, group and individual accountability, promotive interaction, appropriate social skills, and group processing. Positive interdependence is the result of each student’s individual success being dependent upon the success of the group. To structure positive interdependence, it is essential that each student have a unique and necessary role in the group. Group accountability exists when the teacher assesses the performance of the entire group, and individual accountability is the characteristic that prevents some group members from benefiting from the work of others without offering any contributions. Structuring activities with individual accountability in mind requires the assessment of the activity to be dependent upon the assessment of individual contributions. For example, the group score on an assessment should be based on what each member scores on the assessment individually. If the group were to be assessed on a single submission, then it would be much easier for one or several of the group members to relax while one or a few do the majority of the work. Johnson and Johnson include the idea of promotive interaction as also being critical to the success of cooperative learning groups. By promotive, the Johnsons mean that the interactions between group members must support the learning activities of each group member. There must be an ethos of support and encouragement between group members. They argue that the interaction must be face-to-face, but as previously noted, technological advances in the years since Johnson and Johnson originally published their recommendations now allow remote students and teachers to interact in virtual face-to-face settings. The final two essential characteristics of well-structured cooperative learning activities are that the teacher provides sufficient training in the social and interpersonal skills necessary for effective group work and that the group be required to evaluate or process their effectiveness as a group.

Related to the need for group members to be trained in appropriate interpersonal and social skills is the notion of “shared regulation” in learning (Järvelä, Järvenoja, Malmberg, & Hadwin, 2013, p. 269). Shared regulation occurs when group members create and monitor plans for learning and monitor their progress as a group, and involves the group sharing specific metacognitive strategies such as “controlling motivation, cognition, and behavior” (Järvelä et al., 2013, p. 270).

Slavin (2011) identifies four possible mechanisms by which well-structured cooperative learning activities might affect student achievement and then suggests a model integrating the key ideas from each of the mechanisms. The first two processes that seem to be at work are related to student motivation. It is possible that working cooperatively provides motivational incentive for students to learn the material carefully because they want to get good grades, or that cooperative learning activities promote social cohesion, leading to positive social pressure from peers. Both of these mechanisms rely on the presence of positive interdependence in the activity. Two other possibilities are based more on the cognitive changes that are enabled by cooperative activity. The first is the suggestion that working with peers is developmentally advantageous as there are many opportunities for students to be challenged within their zones of proximal development (Vygotsky, 1978) by their peers who are just slightly more capable. The other is based on the long-held notion from cognitive psychology that in order for students to retain new information, they must restructure or elaborate on their previous understandings. One effective method of promoting that cognitive elaboration is to have a student explain a concept to a peer.

Slavin (2011) proposes that each of these processes can be integrated into a single model showing how cooperative learning activities might affect student achievement (Figure 4).

Figure 4. Integrated theoretical model of cooperative learning processes

In Slavin’s model, the learning activity must be designed primarily to promote positive interdependence, where the achievement of the group depends upon the learning of all group members. When positive interdependence is a characteristic of the learning activity, Slavin proposes that group members are more motivated to learn for personal and social reasons and that there is a greater sense of social cohesion. Furthermore, increased motivation to learn and increased social cohesion are mutually reinforcing. These personal and social drivers then provide the conditions necessary for group members to engage in deeper approaches to learning, where they explain concepts and misconceptions, form and defend positions and debate the merits of ideas.

It might be useful to conceptualize Slavin’s model as a farm, where the farmer’s tools like tractors and ploughs are analogous to the learning activities and must be designed to suit the objectives of the task at hand. When the tools are well designed, the farmer is able to till the soil, much like a teacher uses learning activities to enhance students’ motivation to learn and help each other. The tilled soil, then, represents the ideal conditions for the seeds to grow and mature, much like students’ ideas will become more mature through the processes of peer support and cognitive restructuring.

It is also important to recognize the importance of intellectual conflict between group members. Johnson and Johnson (1999b) contend that the process of presenting and actively defending a view and developing and presenting a carefully reasoned response to legitimate criticism, in their words, intellectual conflict, is highly desirable if the goal of the learning activity is to promote critical thinking and clear communication. If such intellectual conflict is handled appropriately by group members who have been taught and have practiced the interpersonal and group skills necessary to argue constructively, then teachers can expect to see reduced levels of self-confidence in students’ views leading to a continued search for information and, consequently, further cognitive elaboration and practice of critical thinking skills. The Johnsons also note that students working alone, and this author would add, especially those working alone in online distance learning contexts, do not have the opportunity to hone their ideas against those of other students.
 
## Critical Thinking {-}


Dewey (1910) was among the first and one of the most influential theorists to describe in some detail what we now typically call “critical thinking.” Dewey describes thinking as occurring on three different planes. First, he describes thinking as being simply the goings on in a person’s mind. At this level, thoughts are generally trivial and inconsequential. Second, Dewey describes thinking as a purely mental event. According to this criterion, perception of a lamp that sits on a desk is not considered to be thinking, but remembering the feeling of riding one’s bicycle down a hill is thinking. The third plane of thinking requires that beliefs must be grounded in some sort of evidence. This plane is actually composed of two different levels of thought. Beliefs for which the basis of their truth has not been considered characterize the first level. An example of this kind of thinking might be the belief common among very young children that the sun actually goes up and down and is in motion across the sky. There is certainly evidence that supports this belief and it is understandable why children would form the belief. But when children have matured and are able to consider the evidence in light of an accurate model of the solar system, they typically replace their previous misconception with a model that more closely approximates what is actually true. It is this final plane of thinking that has formed the foundation of what we now call critical thinking. Dewey (1910) further describes this kind of thinking as being an active belief or knowledge that is held due to supporting evidence.

More recent theorists have sought to clarify what is meant by the term critical thinking and in doing so have provided significant insight into the processes, attitudes and skills associated with critical thought. For example, Brookfield (1987) argues that critical thinking is the dual process by which we call into question the assumptions that form the basis of how we typically think and are then prepared to adjust our behaviour depending on the outcome of the process. He says that we must be able to provide justification for our assumptions as well as judge the rationality of our justifications against an objective standard of some sort; so critical thinking is a metacognitive process involving the introspective examination of our typical or habitual ways of thinking. The other part of the process, according to Brookfield, is that we are able to explore and imagine alternative ways of thinking, or alternative justifications that might lead to different conclusions. Brookfield refers to this process as “reflective skepticism” or “cautious intelligence” (1987, p. 21) about claims to truth. Furthermore, says Brookfield, these two processes do not occur outside of the context of active inquiry in a particular discipline. This active inquiry requires the critical thinker to alternate between analysis and action based on the analysis.

Lipman (1988) asserts that critical thinking is based on clear criteria, such as validity, the quality of the evidence and consistency. It is also an iterative process whereby the thinker seeks to find fault with his or her own reasoning and is aware of the context of the phenomenon in question.

Halpern (1989) describes critical thinking as thinking that is purposeful, reasoned and goal directed and the “kind of thinking involved in solving problems, formulating inferences, calculating likelihoods and making decisions” (p. 5). Similar to Lipman and Brookfield, Halpern observes that critical thinking involves a metacognitive process of evaluating the very process of thinking itself and how the thinker came to his or her conclusions.

Bailin, Case, Coombs, and Daniels (1999) describe critical thinking in very similar ways in that it is goal directed, must meet certain standards, and includes the assessment of reasons. They add the idea that there must be a responsible act of deliberation prior to coming to a conclusion that would include the consideration of other alternative views and their justifications. Bailin et al. also delineate five preconditions to good critical thinking:

- The thinker must have some background knowledge of the concepts, beliefs, or facts related to the topic.
- The thinker must understand the requirements of critical thinking in their particular discipline. They must understand what counts as good evidence or justification and what does not.
- The thinker must have knowledge of key critical concepts such as the difference between necessary and sufficient conditions, how to identify different types of arguments and how inferences can be made from premises.
- The thinker must have an understanding of heuristics or strategies for deliberating such as using Venn diagrams or being able to list the pros and cons of each side of an argument.
- Finally, the thinker must have certain habits of mind or attitudes that lead to a desire to think critically.

Hendrickson, St. Amant, Hawk, O’Meara, and Flage (2008) propose that critical thinking is a process used to come to a conclusion about what to believe or do. They contend that it is more than simple logic, which can be reduced to completely symbolic propositions devoid of any content. Rather, they see critical thinking as being employed towards the practical application of reasoning through considering four basic questions.

- What does the statement claim?
- Is the statement true or false?
- What reasons are there to believe that the statement is true or false?
- How good are the reasons for believing that the statement is true or false?

Based on the review of the definitions presented above, the salient descriptors of critical thinking used for this thesis research included the following:

- that critical thinking is purposeful, or goal directed (Bailin et al., 1999; Halpern, 1989; Hendrickson et al., 2008);
- it is a metacognitive process which leads to the examination of assumptions, rationales, and justifications (Bailin et al., 1999; Brookfield, 1987; Halpern, 1989; Hendrickson et al., 2008; Lipman, 1988);
- it includes the consideration of alternative ideas (Bailin et al., 1999; Brookfield, 1987);
- it is dependent upon the willingness of the individual to engage in the process of thinking (Bailin et al., 1999).

## Fostering Critical Thinking Skills {-}

There is very broad support in the literature for the need to promote and support critical thinking skills (Garrison & Cleveland-Innes, 2005; Green, 2005; Kanuka, 2005; Lunney et al., 2008). This section assesses evidence from research literature to support the ideas that taking deeper approaches to learning tends to lead to the development of critical thinking skills, and that deep approaches to learning should be a specific design goal of learning environments.
Approaches to learning.

According to Biggs et al. (2001), two categories of factors precede learning tasks. First, students will approach learning tasks according to their preferences, abilities, and prior knowledge. Second, teachers will design the learning task in alignment with, for example, the course objectives, style of assessment and/or institutional priorities. These two sets of factors have a role in influencing how a particular student will approach a particular task. Both of these categories of factors influence the students’ actions in relation to the learning task, and it is these actions, or approaches to learning, that determine how well the students attain the learning objectives.

Biggs et al. (2001) refer to this phenomenon as the 3P model of teaching and learning (Figure 5) where student factors and the teaching context influence the process in which students engage during the learning activity and the products of their efforts. The two-headed arrows between each of the elements of the model indicate that each element influences and is influenced by each of the other elements.

Despite the mutual influence among the elements of the model, the most important element in an educational context is the processes in which students engage and the approach that they take to the learning task.

Figure 5. The 3P Model of Teaching and Learning (Biggs et al., 2001, p. 21)

Biggs quotes Shuell (1986, p. 429), who states,

> If students are to learn desired outcomes in a reasonably effective manner, then the teacher’s fundamental task is to get students to engage in learning activities that are likely to result in their achieving those outcomes. It is important to remember that what the student does is more important than what the teacher does.

It is critical to note that the 3P model is dependent not only on the student’s predispositions and academic abilities, but it depends also upon the design of the learning activity to encourage students to take deeper approaches to their learning. According to Biggs and Tang (2007), students can take either a surface or a deep approach to a learning task. Students relying on low-level cognitive skills for tasks that require high-level cognitive skills demonstrate a surface approach. Students using a surface approach are more concerned with getting the learning task out of the way quickly to meet the requirements with minimum effort. They memorize isolated facts when an understanding of how ideas are connected is necessary (Ramsden, 1992).

Deep approaches to learning, according to Biggs and Tang (2007), are characterized by the appropriate use of high-level cognitive skills for tasks that require them. Students taking a deep approach seek to understand ideas in context and apply their learning to other concepts. They actively consider their own questions and seek answers related to the idea. In short, students taking a deep approach to their learning are doing the things required of critical thinkers.

To illustrate the differences between the two approaches, imagine that Student A is relatively uninterested in the topic of study and only needs a minimum score to obtain credit for the course, he or she may be more likely to approach a multiple choice assessment very superficially by memorizing facts from the textbook. Conversely, if Student B is highly self-motivated, interested in the topic, and has broad prior knowledge of related topics, he or she may be more likely to take a deep approach to a competency-based portfolio assessment. Interestingly, Biggs et al. (2001) would predict that Student B may also take a surface approach to a learning task if the teacher indicates that the task is relatively unimportant, or if the teacher only uses multiple choice assessments to assess factual knowledge. Biggs et al. are explicit in their belief that student approaches to learning are not fixed or pan-contextual.

Grounded in the idea that the activities in which students engage, or their approach to learning, have the most significant effect on how much they learn (Biggs & Tang, 2007; Marton & Säljö, 1976), Garrison and Cleveland-Innes (2005) provide a strong rationale for the argument that instructors who want their students to think critically in their discipline of inquiry must be intentional in how they design the interactions in their courses. Using Garrison, Anderson, and Archer’s (2000) Community of Inquiry model as their foundation, Garrison and Cleveland-Innes (2005) used the Study Process Questionnaire (Biggs et al., 2001) to measure how students in four graduate-level courses approached their learning over the duration of the course. They found that course design and teacher presence were critical to encouraging the online learners to take a deep, meaningful approach to learning. There was a profound shift from surface towards deep levels of learning only in the course that was specifically designed to engage students in critical thought. They concluded that in order for deep, meaningful learning to take place, attention must be paid to structuring quality interactions in the design and facilitation of online distance learning environments, rather than simply increasing the quantity of interactions.

Green (2005) examined the factors influencing critical thinking in computer conferencing with a specific focus on health professionals. Her case study focused on the experiences of 10 rehabilitation health professionals who had completed a graduate-level course on reasoning and decision-making. Analyzing data from computer transcripts, interviews, and learner journals, Green concluded that computer conferencing provided students with the opportunities to reflect and increase their understanding, verbalize tacit beliefs, and explore ideas more deeply. She also found that instructors could influence critical thinking through facilitation techniques and purposeful instructional design. Green’s study provides support for the use of computer conferencing through discussion forums as long as the discussion activities are well designed and appropriately facilitated. However, Green’s study did not explore alternative activities, such as study buddies, which can be implemented in contexts that do not support discussion forums. Another limitation of Green’s study is that the course content itself addressed critical thinking, a confounding factor that may have influenced the findings. It is possible that recall of the course subject matter, rather than actual learner skills, provided evidence of critical thought.

Kanuka (2005) investigated the role of various instructional strategies in facilitating higher levels of learning in an online environment involving 19 adult learners enrolled in an online degree program. Five different instructional strategies, (nominal group technique, debate, invited guest, brainstorming and WebQuest) were transferred from face-to-face environments and hosted in the discussion forums of a selected course in the program. All five strategies were specifically designed to facilitate higher levels of learning.

Kanuka used the Structure of the Observed Learning Outcome (SOLO) taxonomy (Biggs & Collis, 1982), which classifies student responses into five categories reflecting the complexity of the response. Prestructural responses are simplistic and indicate that the student does not understand the concepts; unistructural responses include one or two relevant facts or ideas about the concept; multi-structural responses include several relevant facts of ideas, but they are not related to each other; relational responses integrate several facts or ideas into a coherent whole; and extended abstract responses are relational responses generalized to other contexts or metacognitively applied back to the original context.

Kanuka found that the five instructional strategies were successful in promoting higher levels of learning but that not all strategies worked equally well. For example, the nominal group technique generated five prestructural or unistructural responses and only seven relational or extended abstract responses, whereas the WebQuest activity generated no prestructural or unistructural responses and 17 relational or extended abstract responses. Kanuka suggested that the nominal group strategy was less successful because it was a more individualistic activity and that it was implemented too early in the course. The WebQuest was successful because it required students to consider multiple views on complex topics. Kanuka did not mention the idea of positive interdependence in her comments, but it seems clear from comments like the following from one of the participants that the activity promoted positive interdependence:

> this activity provided the opportunity for collaborative learning contrary to typical online collaborative group work, where one person usually ends up doing all the work. The WebQuest allowed each member to do their part by playing a specific role. (Kanuka, 2005, “Webquest” para. 3).

Limitations of Kanuka’s investigation include acknowledged issues with validity and generalizability and calls for further exploration of different collaborative instructional strategies.

In an article addressing an activity similar to the study buddy activity investigated in this thesis research, Morss and Murray (2001) explored the use of study buddies in the development of academic writing skills, particularly related to output and confidence. They encouraged participants in their writing program to meet with a study buddy every two or three weeks to support each other in writing by discussing their progress, sharing strategies, and giving each other feedback. Participants indicated that the study buddy activity was an important learning experience because it provided a sense of motivation and urgency with respect to deadlines and it also provided an avenue to discuss their work with someone else which improved their revision process. It is also important to note that participants reported that the study buddy should be well structured to prevent off-topic or counterproductive meetings. Morss and Murray concluded that the activity was effective in increasing writing output and also increasing students’ confidence in their writing abilities.

As numerous theorists have pointed out (Brookfield, 1987; Dewey, 1910; Halpern, 1989; Johnson & Johnson, 1999a; Lipman, 1988), the process of getting feedback, considering alternative viewpoints, questioning assumptions, and peer teaching are important critical thinking skills, and those are the skills which are required during activities such as the study buddy.

## Chapter Summary {-}

This chapter provided a review of the scholarly literature relevant to this investigation into the study buddy activity. It began with a discussion of social constructivism as the theoretical foundation for the research. It demonstrated that Vygotsky’s theory of the zone of proximal development, which describes how students learn in social contexts, was foundational to cooperative learning theories, upon which this thesis research is based. The characteristics of cooperative learning were described in light of Slavin’s (2011) model of how cooperative learning activities affect student learning.

The next section was a discussion of critical thinking, including a description of the characteristics of critical thinking and a discussion of literature related to how critical thinking can be fostered in online higher education. A key concept in promoting critical thinking is the idea that students may take either a deep or a surface approach to their learning, depending upon various factors such as their personal learning preferences, their prior knowledge, and the characteristics of the design of the learning activities. The chapter concluded with a discussion of several scholarly reports that describe investigations into strategies for promoting critical thinking and deep approaches to learning in online higher education.

 