# Qualitative Analysis and Results


## Philosophical Foundations of Phenomenology {-}

Creswell (2007) urges practitioners of phenomenology to discuss the philosophical foundations of phenomenology prior to engaging with the process, pointing out that Moustakas (1994) uses over 100 pages to outline the philosophical foundations before discussing the methodology associated with this qualitative approach.  Based on the writings of Husserl (1929), Moustakas (1994) and van Manen (1990) describe two different ways to think about phenomenology. van Manen’s hermeneutic phenomenology approach is much more focused on the researcher’s interpretation of events through various written texts; whereas Moustakas’ transcendental approach includes the step of the researcher “bracketing” or describing his or her experience related to the phenomenon in order to eliminate any presuppositions in the analysis (Creswell, 2007). The term “transcendental” refers to Moustakas’ (1994) belief that the researcher, having bracketed his or her own experience, will be able to perceive the phenomenon “freshly, as if for the first time” (p. 34). Common to both approaches, however, is the idea that the phenomenon being described is a conscious one and that the descriptions of the phenomenon are descriptions of the “essence” of the phenomenon.

This phenomenological investigation followed the procedures outlined in Creswell’s (2007) protocol, which follows the structure advocated by Moustakas (1994), but also van Manen’s (1990) recommendation that the phenomenological task is one in which texts are interpreted, not only described. The texts in this study were submitted in response to open-ended questions asked throughout the survey.

A central tenet of contemporary understandings of the phenomenological process is the belief that the phenomenon in question is about something in the real world. This can be seen first in Husserl’s insistence that “The basic property of all manners of consciousness in which I live as ego is, as we say, its intentionality — is being consciousness [sic] of something” (emphasis added) (1929, pp. 10–11). Husserl’s argument was echoed by van Manen (1990) who argued: “Hermeneutic phenomenological human science is interested in the human world as we find it in all its variegated aspects” (emphasis in original) (p. 18). Moustakas (1994) is also clear that phenomenology seeks to understand something in the external world; he claims that “directness is an intrinsic feature of intentionality, that the mind is directed toward some entity” (emphasis added) (p. 28). All three are reliant on the idea that consciousness requires intentionality.

So consciousness is always about or of some object or phenomenon, and phenomenology is a method used to describe people’s experience of that object or phenomenon. In this study, the descriptions are based on the statements given by the graduate students who experienced the phenomenon of the study buddy activity in the course they were taking. The messages conveyed in the statements are assumed to correspond to what the participants actually experienced during the study buddy activity. This assumption does not mean that these descriptions capture the entirety of the phenomenon in complete detail. Rather, the descriptions capture the essence of the phenomenon, or as van Manen (1990) would contend, the descriptions are heavily reliant upon the researcher’s interpretation of the phenomenon, based on the information gathered from the participants.

## Step One: Bracketing {-}

The phenomenological process used to understand an experience typically begins with the researcher “bracketing” his or her experience related to the phenomenon. Husserl (1929) and Moustakas (1994) believed that it is only by the researcher being explicit about his or her experiences, can he or she truly see and understand the phenomenon with a natural attitude, or an attitude of taking no position with respect the phenomenon at hand. In fact, Husserl (1929) advocated that the researcher should not take a position about anything in the world while engaging in the phenomenological process. While completely bracketing one’s own experiences seems a tall order, van Manen (1990) argues that because the phenomenologist’s task is to describe a human experience, which may very well be a universal experience, there is value in the researcher describing and setting aside his or her own experiences during the research process.
The researcher’s prior experience with the study buddy activity.

As this section of the thesis is specifically intended to describe the author’s personal experience with the phenomenon in accordance with accepted phenomenological practice, it has been written in the first person and set apart from the rest of the thesis.

> My own experience with the study buddy activity occurred three years ago in the same course that I used in my thesis research, MDDE 604: Instructional Design in Distance Education. However, there was a different instructor who put a slightly different structure in place for the activity.

> The activity in my experience was described as a peer review, it was mandatory and worth 10% of the final grade. Peer review partners were required to submit their completed projects to each other and then provide critical, yet collegial and professional feedback based on the requirements of the assignment. Feedback was then returned to the partner as well as to the course instructor who assessed the quality of the review.

> We were on our own to find partners through the discussion forum in the course. There was no mention of the notion of bears or bunnies with respect to finding compatible partners, nor were there specific guidelines on how we should communicate. My partner for the activity was a student from the Nursing program taking a course in the Centre for Distance Education; she was not as familiar with educational jargon as some others might be.  A full three years later, I remember that the topic that she covered in her material had to do with personal hygiene in a hospital environment and I found the material both interesting and informative. I remember very little about any problems with her work, nothing about the feedback that I gave her and nothing about the feedback that she gave me. While, my memory of the specifics of our interactions is limited, I retained copies of our conversations. I do, however, remember her name, that she was (is?) a nurse, and the city where she lived at the time. I also remember that the experience was a very positive one for me and, I think, for her. We kept in touch occasionally for a year or so after the course ended, but since then have been out of contact.

##  Step Two: Significant Statements and Horizontalization {-}

The second step in Creswell’s (2007) phenomenological methodology is to develop a list of significant statements from the data. Given that the data were submitted in written form, this was a hermeneutic phenomenology analysis, the search for understanding about a human experience through written texts.
Participants in the study were asked to write a few sentences to explain in more detail their responses to the quantitative survey items. These responses totaled about 4000 words. The data were compiled into a spreadsheet and imported into QSR NVivo 9 ™ for analysis.

The written responses were first read multiple times to allow the researcher to become familiar with the nature and tone of the responses. Coding was then conducted per-question, rather than per-participant. The codes were generated based on the researcher’s interpretation of the responses provided for each question.

A total of 959 passages were identified as being relevant to the research questions. From these passages, 84 discrete codes were identified.

NVivo allows the user to create a hierarchy of codes; therefore, codes were sorted into themes in alignment with the research questions. These coded passages, or significant statements, were transferred back to a spreadsheet. Then, in a process called “horizontalization” (Creswell, 2009), each statement was treated with equal value and overlapping or repeated statements were removed from the list of significant statements.

The result was a total of 227 significant statements organized into 65 minor and four major meaning units or themes. The list was further reduced through a process of eliminating those statements that were deemed to be less relevant to the research questions. The reduced list included 80 significant statements in 18 minor and four major themes. The four major themes focused on the following:

- the student’s approach to learning and the cognitive skills generally employed by students in the course;
- the value derived from the study buddy activity;
- recommendations about the structure of the study buddy activity;
- the experience of those who chose not to participate or the negative experiences of participants in the study buddy activity.

## Step Three: Textural Description {-}

Creswell (2007) recommends that phenomenologists construct a formulated meaning from each of the themes identified from the data, which is then integrated into a textural description of the phenomenon or a description of what happened.
Major theme 1: Approach to learning and cognitive skills.

Although the quantitative analysis showed no significant difference between the approaches taken by participants and non-participants in the study buddy activity, there was evidence in the qualitative data that the students in the course already tended to take a deep approach to their learning by utilizing the high-level cognitive skills associated with deeper approaches, such as extension and application, both of which are indicative of critical thinking. For example, one student wrote

> I also buy books or download research articles that enrich or contradict the course readings.

Another student wrote

> [I] try to explore as much material as I feel is needed to make up my own conclusion/opinion on the issue.

Many students also reported that they try to extend their understanding of course concepts by seeking alternate and other recommended resources. One student wrote

> [I] look up alternate sources to the material in books/articles from previous courses and in the AU library;

another stated,

> [I undertake] further exploration of the same key words/topics on the internet to find the latest information if readings seem a bit out of date.

Another key strategy described by students in the course was that of seeking to apply course concepts to their own work context. For example, a student wrote,

> I approached each topic with these questions: ‘What here applies to me and to my work?’  ‘How might this help me with my work?’

Another student reported

> Being able to relate what I read to work is enlightening.

As noted in the review of the literature, among the features that scholars have identified to describe critical thinking is that the learners must be willing to engage in the process of critical thinking, that they examine justifications, and consider alternate viewpoints. The participants in this study clearly demonstrated a willingness to seek out readings to enrich the course readings, as well as contradictory viewpoints. By doing so, they were considering the rationale for their own opinions in light of the opinions stated in the course readings, an important feature of critical thinking. The desire and ability to form an educated opinion about course concepts is indicative of quality graduate-level studies.
However, missing from these activities was the opportunity for students to defend their views against others who actively advocated a different view. Extending knowledge through seeking alternative or challenging articles, books or other media, and applying concepts to relevant contexts are certainly positive, but these activities could be seen as being relatively passive, risk-free instances of critical thinking in comparison with actively challenging another person’s ideas. As discussed in the next section, participants in the study buddy activity reported that the activity pushed them to do more than simply seek out static resources and actually consider alternative viewpoints.
Major theme 2: The value of the activity.

Participants in the study buddy activity reported that the activity was valuable to them because of the social connection it provided in an otherwise lonely learning environment, the benefit of an alternate viewpoint, and the motivation to complete the work on time (Table 16).

Table 16

Participants described the activity as enriching and providing emotional support, comfort, encouragement, and even intimacy with someone with whom they could share frustrations about the course. Furthermore, they emphasized the importance of trust and respect in the success of the activity. One participant wrote,

> I think that working with a good editor, whose opinion one trusts and values, improves learning overall.

Another said,

> I think that the study buddy option was of value because I like and respect the opinions of my Buddy.

The trust and respect present in the study buddy relationship was reported to have a positive effect on the learning experiences of one participant, who wrote:

> I think it is very important to trust and respect the feedback you receive from peers. I think that when there is a mutually trusting relationship, we can give and receive feedback more honestly and openly.  If my buddy suggested something I did not like, I would ask myself why he thought that – or I would just ask him directly. This allowed for good learning because neither of us were concerned about hurt feelings.

The relationship between the social benefits of the activity and improved learning was further supported by reports from participants that the activity provided what Slavin (2011) calls peer motivation to study. Participants felt that they would be letting their study buddy partner down if they did not get their work completed in enough time to allow for peer review and revision. As one participant noted,

> I was motivated to complete work in a timely manner so that my “buddy” could review my work without being rushed.

Another indicated,

> [We] knew there was someone out there who depended on us to have work completed on time.

The peer motivation was not only focused on getting the work done on time, however; one participant reported:

> [my study buddy] also helped me stay in the course because I had committed to being a peer reviewer

suggesting that, for this student, the activity was a factor in her decision to persist in the course because of her promise to her partner.

With respect to promoting deep approaches to learning and critical thinking skills, participants in the activity indicated that, beyond the deep strategies they already employed, they also valued the opportunity for collegial exchange and debate with their partner’s alternate viewpoint. This type of interaction went beyond the search for alternate viewpoints in the literature, providing a situation where the alternate viewpoint was coming from someone they knew, trusted, and respected, as well as an opportunity to incorporate their partner’s ideas into their own. For example, one participant reported,

> [I] got to see another’s work that caused me to consider an alternative point view and to contribute my perspective of their work.

It was not only the feedback that they received from their partner that was valuable to participants  (e.g., “My study buddy gave a different perspective in how she perceived my writings.”), but also the ability to read their partner’s work (e.g., “I have been able to get a better understanding of the course content and how it is applied by reading others’ work.”).

Participants reported that being exposed to an alternate viewpoint from a trusted peer and then having to provide collegial and constructive feedback helped them to improve their reasoning with respect to course concepts. One participant noted,

> At the same time I found that at the beginning just by trying to help improve assignments of my study buddy and talking about them helped me to improve my thinking and logic.

A second participant wrote,

> [My partner was] even better at seeing where I needed to expand an argument and where I could cut back on unnecessary detail.

Another student appreciated having a partner to whom he could direct his explanations as indicated in the following:

> My study buddy became my audience as I was writing—I was writing to explain the material to her. In turn, she was able to point out gaps in my reasoning, to question what I meant and to help me sharpen my ideas and arguments.

Interestingly, there were very few references to the idea that the study buddy activity resembled the peer review process that is so highly valued among academics, and those who did mention it seemed to downplay the significance of it. For example, one participant wrote,

> I used the study buddy only to peer review papers,

suggesting that the peer review process was more cursory and focused on grammar and punctuation rather than a critique of ideas and justifications.

To summarize, participants described the value of the activity as being a combination of the social and emotional support that they received from a trusted peer which led to a collegial relationship and the opportunity to consider an alternate viewpoint leading to greater depth of thought and improved reasoning.
Major theme 3: The structure of the activity.

Garrison and Cleveland-Innes (2005) argue that the design of the learning environment is a very significant factor in whether or not learners will take a deep approach to their learning and utilize critical thinking skills. In other words, the learning activities must be structured to encourage learners to take a deep approach. In view of this recommendation, participants were asked whether they thought the study buddy activity should be mandatory and structured or voluntary and student driven. Their responses were evenly divided between the two options (Table 17).

Table 17

Many participants thought that the activity should be mandatory and structured because of the benefits that they experienced from having participated in the activity and the likelihood that many students would opt out of the activity if it were voluntary. One participant indicated,

> I think that the benefits are very positive, and if this activity were left to the students to initiate on their own, many would choose the less ‘involved’ route;

another participant wrote

> If left to their own devices, few would likely choose it because of the additional time required.

Another participant related that he had participated in a similar activity in a previous course, saying

> I think a Study Buddy option or some other means to create small study groups is an important student support mechanism for distance learning.  I have benefited greatly in other AU MDDE courses when I have participated in such groups.   But they don’t seem to spring up spontaneously, they typically seem to require some official sanction from the instructor to kick start them.

Another reason why the activity should be mandatory came from a participant who wrote,

> Formalizing it in the course gives an impetus to try it out. Some may choose to continue it themselves in the future, I certainly would like to.

The desire to use the strategy in future courses provides support for the idea that the activity is a valuable learning tool for distance students.

Interestingly, there were two instances where students used the same rationale to come to the opposite conclusion, i.e., that the activity should be voluntary. One participant wrote,

> Peer review is important, especially for instructional design. No one person has all the experience so multiple points of view are valuable. People will organize based on their own needs.

A further instance of conflicting rationales is evident in the following quotes:  In support of making the activity mandatory, a participant stated,

> It doesn’t always work out so… it should have more structure to start us off;

whereas in support of keeping the activity voluntary, another student wrote

> It doesn’t always work out so it should be left to us without a grade.

Other students who felt the activity should be voluntary thought so because of the risk of ending up with an incompatible partner, for example,

> Unless you have a good learning partner experience, it is better to organize your own partner.

and

> There isn’t sufficient time to select a study buddy from a pool of unknowns if there is no one you know from prior study. In that case, I would sooner work alone.

In recognition of the trade-off between the learning value of the activity and the perils of working with peers, one participant wrote

> Even though we learn from each other, it is important to recognize that we have different writing styles, levels of experience, and personalities. I believe the Study Buddy to be a valuable learning experience and will continue on with the relationship that has been developed. But I also recognize there are individuals in my class where the SB process would have been very time consuming and frustrating.

It is clear from the data that participants thought the ability to negotiate with their partner was important to the success of the activity. Participants indicated that the activity works best when study buddy partners are allowed the flexibility to negotiate with each other. For example, one participant wrote

We worked together to negotiate timelines that worked for each of us, and we kept to those timelines to within a few hours.

Another stated,

> We started with a preliminary schedule for the course and getting out work sent to each other. Then, as things changed, we kept each other appraised of delays and other personal obstacles.

Yet another participant noted,

> We developed a timeline and agreed to an exchange date for our assignments.  We agreed to allow each other to put a hand up and say that we needed more time, without question.  It was a very collaborative relationship.

This process of negotiation aligns well with the importance of shared regulation in learning where group members co-create the structures by which they will engage in and evaluate the metacognitive processes required for successful group cooperation (Järvelä et al., 2013).

Given the even split between those who advocated for the activity to be mandatory and those who thought it should be voluntary, the similarity of the rationale for their opposing views, and the recognition from both sides that the opposing view had merit, there was no clear indication of whether the activity should be voluntary or mandatory. Further research into the ideal structure for the activity is warranted.
Major theme 4: Negative experiences and the views of non-participants.

A key to understanding the full complexities of a phenomenon is to consider the views of those who have views contrary to the prevailing view, an idea supported by the literature on critical thinking (Brookfield, 1987). Study buddy participants who had a negative view of the activity were very clear that the greatest frustrations occurred when there were inequities in either partner’s motivation or in the quality and depth of the feedback received. Others noted that the workload associated with the activity was, at times, problematic (Table 18).

Table 18

A participant with a less motivated partner wrote,

> Most of the time I felt that I [was] wasting my time trying to help someone who did not want to be helped…I found him clearly stubborn and he did not want take any suggestions from me.

In at least one instance, this incongruent motivation caused the more motivated partner to quit the activity and write

> When I realized that he was there [to] simply pass the course – I gave up.

Another source of frustration occurred when the participant received extremely superficial feedback such as

> It looks perfect.

A participant wrote

> The study buddy returned comments to assignments that were superficial in nature. [I] didn’t see their attempt to ensure I was directly answering the assignment requirements.

A third participant wrote

> I helped more than I received,

expressing frustration that seemed to be shared by others with partners who didn’t seem to put much effort into the activity.

Those who commented on the extra workload reported that it was sometimes a problem, but at least one participant indicated that the extra workload was worth it in the end. One participant wrote

> Valuable time was spent by both in a very demanding course.

Another wrote

> I suppose the only negative aspect would be the additional time required to coordinate efforts. This I believe is outweighed by the positives.

Those who chose to not participate in the study buddy activity did so for the same reasons expressed by those who participated and had a negative experience. The non-participants were concerned that they would either end up with a partner with whom they would find it difficult to work or that they would not have enough time to be a good partner for someone else. One non-participant wrote,

> [I] did not want to risk ending up with someone I did not mesh well with.

and another wrote,

> I do not enjoy group work. I would rather complete my work on my own.

Still another non-participant wrote,

> Also, my main reason for not participating was that I didn’t feel I could do my partner justice with my busy schedule.

## Step Four: Structural Description {-}

The structural description, according to Creswell (2007), is a description of how the phenomenon occurred and in what setting.

The phenomenon that is the basis of this investigation is called the study buddy activity that is included as a voluntary component of MDDE 604: Instructional Design in Distance Education at Athabasca University. MDDE 604 is required for graduate students in the Master of Education (Distance Education), the Post-Baccalaureate Diploma in Instructional Design, and the Post-Baccalaureate Certificate in Instructional Design programs. The course also attracts a number of non-program students, particularly nurses, who take it as an elective for their own program. MDDE 604 has as a prerequisite course MDDE 603: Foundations of Instructional Design: Systems Analysis and Learning Theory.
Summary of the activity.

Each study buddy participant was first to find a partner who agreed to work with him or her for the duration of the course. Three days prior to submitting their first assignment, the study buddy partners exchanged drafts of their work and they were each responsible for providing critical feedback to their partner based on the requirements of the assignment. Upon receipt of the feedback, and prior to submitting their final draft, each partner then had the opportunity to incorporate, or not, the feedback that they had received. The study buddy partners engaged in this same process in each of the remaining assignments in the course. Finally, they provided a brief written reflection on their experience along with samples of their exchanges in order to receive the bonus marks.

The study buddy activity was a cooperative learning activity introduced specifically for the purpose of generating task-focused student-student interactions to encourage deeper approaches to learning and more critical thinking among distance learners. Although students were cautioned that work habits could make or break a study buddy team and “quick working bunnies” should avoid matches with “procrastinating bears,” no additional structure was provided with respect to how the study buddy partners should interact with each other during the study buddy activity. In reviewing several terms of study buddy reports, Richards (personal communication, 2012) noted that not all pairings work well, but for the majority that do, the learners reported improved on-task focus and a better understanding of the content. In some cases, study buddies have gone on to enroll in other courses together and continue to study cooperatively. He suggested that the study buddy activity be encouraged for other online courses.

For a more complete description of the context of the study buddy activity, please see Chapter I.

## Step Five: Composite Description {-}

The final step in Creswell’s (2007) recommended process for phenomenological analysis is to create a composite description of the phenomenon that blends the textural and structural descriptions into an exhaustive description of the researcher’s interpretation of the essence of the phenomenon. The composite description is provided below.

Online distance learning is an often isolating and lonely experience and many participants are mid-career professionals returning to school after an extended absence. It was previously common for students in MDDE 604 at Athabasca University to struggle with writing at an appropriate academic level, so the instructor decided to incorporate a small-scale peer review and feedback mechanism to provide academic and social support for students. When surveyed for their views on the study buddy activity, students’ responses fit into four major themes:

- approach to learning and cognitive skills,
- the value of the activity,
- the structure of the activity, and,
- negative experiences and the views of non-participants.

Students in MDDE 604 demonstrated an existing willingness to engage in deeper approaches to learning and utilize cognitive skills indicative of critical thinking, such as applying their learning to their work outside the course and extending their understanding by seeking out alternative opinions in journals and books. Those who participated in the study buddy activity indicated that the activity encouraged them to go beyond these critical thinking activities and engage in active discussion with their partner who provided an alternate viewpoint. These participants reported that their engagement with these deeper cognitive skills improved their reasoning and the quality of their work. They also reported that they felt very supported and connected as a result of engaging with a trusted and respected peer through the activity and that they were more motivated to complete their work far enough ahead to allow for the peer review process. Students were divided in their opinions of whether the activity should be voluntary or mandatory and often used the same rationales to come to opposing conclusions on the question. They were united in their view that the activity must allow for negotiation between study buddy partners with respect to the timing of their submissions to each other. Those who had a negative experience with the activity reported that the frustrations stemmed from incongruent motivations, where one partner was seen to be doing the minimum required to pass the course, or from inadequate or superficial feedback from their partner. While participants noted that the extra workload was significant, they reported that it was worthwhile. Those who chose not to participate in the activity cited a desire to work alone, the time involved in the activity, and the fear of getting a lazy partner as reasons for opting out.

## Chapter Summary {-}

This chapter was a description of the phenomenological analysis of the qualitative data. It began with a discussion of the history and philosophy of phenomenology, then continued with a discussion of the methods of phenomenology embedded in the actual results of the analysis.

The chapter described the first task of the phenomenologist as bracketing by describing in detail his or her own experience with the phenomenon in question. The next section was a description of how the data were analyzed, first by a thorough reading of the data, then categorizing significant statements in the data by applying codes. From there the chapter described the process of horizontalization, where the researcher eliminated overlapping or repeated statements. The next section of the chapter was the textural description where the researcher gathered the significant statements into themes and provided a formulated meaning statement for each of the themes. This investigation resulted in four themes, which aligned with the three research questions as well as a small theme related to the views of non-participants. The textural description was a description of the researcher’s interpretation of what happened during the phenomenon. Following the textural description was the structural description, which described the context of the phenomenon and how it happened. The final section of chapter 5 was the composite description, which combined the textural description and the structural description, capturing the essence of the phenomenon.

