# Conclusions


This thesis began with a description of the dual challenges of increasing levels of student engagement and also promoting academic rigour in higher education. A significant complication faced by those attempting to address both of those issues is that Arum and Roksa (2011a) found that students who are more socially engaged tend to show less improvement over two and four years in their ability to think critically than those who are not. This investigation was designed to explore the characteristics of a structured study buddy activity as a possible strategy for instructional designers and faculty to include in their courses to increase both student engagement and academic rigour.

Biggs et al. (2001) describe the idea of a student’s approach to learning, which was a key foundational idea in this investigation. They argue that students will either take a deep or a surface approach to their learning depending on various factors such as their own academic history and willingness to engage, the instructor’s design and facilitation practices and the structure of the task itself. A surface approach is described as using low-level cognitive skills for tasks that require high-level cognitive skills. Students using high-level cognitive skills for tasks that require them characterize a deep approach.

Results of the quantitative and qualitative analyses indicated that participants in the study buddy activity were very socially engaged with their partner as a result of the activity and that the activity helped participants to deepen their approach to learning. While there was no significant difference detected in the quantitative analysis with respect to students’ approach to learning (participants in this study typically used deep approaches, even those who did not participate in the study buddy activity), the qualitative findings showed that participants in the study buddy activity engaged in skills that required greater levels of cognitive effort. For example, many students in the course reported consulting recommended readings and searching for alternative views in published literature, but those who participated in the study buddy activity also reported having conversations with their study buddy partners about the course content and working to help each other understand the material in greater depth. This combination of social engagement and academic rigour is evidence that cooperative learning activities like the study buddy activity have a positive influence on student achievement.

Participants were divided on whether the study buddy activity should be mandatory or voluntary, but a clear majority of participants indicated they would participate in a similar activity again and would recommend the activity for students in other graduate-level courses. One of the most significant barriers to participation in the activity was the reticence with which many students approach group activities, usually based on past experiences that ended poorly.

Finally, those who participated in the study buddy activity were clear that the activity and the connection that they developed with their partner was a significant source of emotional and social support despite the oft-cited loneliness of studying in an online setting. This feeling of being supported led to the development of a trusting and respectful context in which the partners could ask questions about course content and receive constructive and sometimes corrective feedback about their ideas.


## Recommendations {-}

Findings from this exploratory investigation suggest the following recommendations with respect to using the study buddy activity or other similar cooperative learning strategies in online distance education:

1. The study buddy activity can be easily implemented in online higher education. Faculty and instructional designers should consider adding this and other structured cooperative learning strategies to their courses.
2. Given that a significant barrier to participation in the study buddy activity was the fear of ending up with a poor partner as well as the lack of consensus on whether the activity should be voluntary or mandatory, a recommended action would be to keep the activity voluntary with a small incentive for providing evidence of participation.
3. Faculty who introduce the study buddy should ensure that the students understand the potential benefits from participation such as the opportunity to consider alternate viewpoints, consider their own views more critically, and the sense of social support that can be enjoyed from working with a trusted and respected peer.
4. One of the reasons why participants had a negative experience with the activity was that they received inadequate or superficial feedback. This concern, combined with the under-representation of the idea of the activity as a peer review process, suggests that the activity be proposed to students as a “structured peer review.”
5. To promote cognitive restructuring or intellectual conflict, faculty should suggest strategies for students to evaluate each others’ work by providing questions for reviewers to ask of their partners such as the following:
	- How did you come to that conclusion?
    - How does this evidence support your conclusion?
    - How do you know ‘X’ is true?
    - Have you considered the evidence against your view?
6. Faculty should consider the following structural ideas from Open Scholar (“Open Peer Review,” n.d.) for the study buddy activity:
	- to encourage greater accountability, make the peer review process open to all course participants by requiring reviews to be posted to a discussion forum;
    - make the review a citable resource;
    - encourage the process of cognitive restructuring by suggesting that participants incorporate their partner’s review of their work into their own.
7. Faculty may want to introduce the study buddy activity on a smaller scale by including it as an option for only one assignment rather than for all assignments.
8. Instructional designers should promote the practice of structured peer review in their course designs for graduate-level online courses.
9. Faculty and instructional designers should consider how synchronous technologies such as SkypeTM Adobe ConnectTM or Blackboard CollaborateTM could be promoted to students as ways to support cooperative efforts.
10. Faculty and instructional designers should consider how asynchronous technologies such as wikis, blogs, or social networking software could be promoted to students as ways to support cooperative efforts.

## Future Research {-}

Future research topics that may be of interest to other graduate students and researchers include the following:

- investigating the Structured Student Interactions model to validate its applicability and utility in online distance learning, especially in light of rapidly increasing access to networks and social media;
- investigating the effectiveness of the study buddy activity in other contexts (e.g., undergraduate, blended, face-to-face);
- investigating the effectiveness of the study buddy activity using experimental methods;
- engaging in a detailed but localized exploration of students’ approaches to learning in face-to-face, blended, and online distance learning environments;
- exploring faculty development issues with respect to encouraging faculty to adopt strategies that lead to deeper approaches to learning in online, face-to-face, and blended environments;
- more thoroughly investigating the structural aspects of the study buddy activity such as whether the activity should be voluntary or mandatory and whether the mix of “bunnies” and “bears” affects the activity;
- investigating in greater depth why students have negative experiences with cooperative learning activities or why some choose to not participate;
- exploring the impact on learning of various software tools such as blogs, wikis, web conferencing software or social networking software when used to support cooperative learning activities;
- investigating the study buddy activity in light of research on shared regulation of learning;
- investigating the role of cooperative learning activities in promoting learner agency.

## Concluding Remarks {-}

There are significant pressures on the higher education system in Canada, from austerity budgets, to massive open online courses to increasing student expectations with respect to technology use and flexible access, to business demands for highly skilled workers who are proficient not only in their craft, but also in thinking critically about complex issues. Higher education faculty and instructional designers have a duty to provide the structure and environment to encourage students to take deeper approaches to learning. In doing so, they will be creating an educational environment that promotes critical thinking, clear communication, and content-specific knowledge. The study buddy activity described and explored in this investigation is a simple activity that can be implemented in a wide variety of educational contexts; it has been shown to increase levels of social engagement in a way that also increases academic engagement. Faculty and instructional designers should feel confident that the activity can improve student outcomes, and students can also know that engaging with the activity will be well worth the time and effort involved.

